# Para gerar o hash da senha, use:
# import bcrypt
# password = 'rdpass'.encode('utf-8')
# hashed = bcrypt.hashpw(password, bcrypt.gensalt())
# print(hashed.decode('utf-8'))
# O hash gerado para 'rdpass' Ã©: $2b$12$07z4L0p0c5F7k9X8Y2H0uO.J6Q9W4T3R1S5V8B7A6C5D4E3F2G1H

credentials:
  usernames:
    rdadmin:
      email: rdadmin@rdservicos.com
      name: Administrador RD
      password: $2b$12$07z4L0p0c5F7k9X8Y2H0uO.J6Q9W4T3R1S5V8B7A6C5D4E3F2G1H

cookie:
  expiry_days: 30
  key: random_signature_key
  name: streamlit_auth_cookie

preauthorized:
  emails:
    - preautorizado@cliente.com
