credentials:
  usernames:
    filipe:
      email: "filipe@rdservicos.com"
      name: "Filipe Pimentel"
      password: "abc123"

cookie:
  name: "rd_cookie"
  key: "segredo_super_seguro"
  expiry_days: 30

preauthorized:
  emails:
    - "filipe@rdservicos.com"
