credentials:
  usernames:
    admin:
      email: "admin@rdservicos.com"
      name: "Administrador"
      password: "123"  # senha em texto simples (ou hashed, se preferir)

    filipe:
      email: "filipe@rdservicos.com"
      name: "Filipe Pimentel"
      password: "abc123"  # pode alterar livremente

cookie:
  name: "rd_servicos_cookie"
  key: "chave_secreta_super_segura"
  expiry_days: 30

preauthorized:
  emails:
    - "admin@rdservicos.com"
