credentials:
  usernames:
    usuario1:
      email: usuario1@email.com
      name: Usu√°rio 1
      password: senha123

cookie:
  expiry_days: 30
  key: "chave_secreta_rdservicos"
  name: "rd_servicos_cookie"

preauthorized:
  emails:
    - admin@email.com
